services:
  fdorganizer:
    build:
      context: .
      args:
        - EXPORT_USER=${EXPORT_USER}
    container_name: fdorganizer
    expose:
      - "8080"
    depends_on:
      - db
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_HOST=db
      - COUCHDB_PORT=5984
      - EXPORT_DIR=/server/export
      - IMPRESSUM_LINK=${IMPRESSUM_LINK}
      - TOKEN_SECRET=${TOKEN_SECRET}
    volumes:
      - ${EXPORT_DIR}:/server/export:rw
      - ./init-flags:/var/flags:rw
      - ./server/static/videos:/server/server/static/videos:ro
    command:
      - sh
      - -c
      - /server/docker_init.sh && /server/start.sh
    restart: always
    user: ${EXPORT_USER}

  db:
    image: couchdb:latest
    container_name: db
    ports:
      - "5984:5984"
    volumes:
      - "./db:/opt/couchdb/data"
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    restart: always

  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - fdorganizer
    ports:
      - "34000:443"
    restart: always

  cron:
    build: ./cron_clean
    container_name: cron
    depends_on:
      - db
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_HOST=db
      - COUCHDB_PORT=5984
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KEYCLOAK_ADMIN}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/realm-config.json
    ports:
      - 8080:8080
    volumes:
      - ./keycloak/realm-config.json:/opt/keycloak/data/import/realm-config.json:ro
    command: ["start-dev", "--import-realm"]
    restart: always