version: '3.3'

services:
  fdorganizer:
    build: .
    container_name: fdo
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_HOST=db
      - COUCHDB_PORT=5984

  db:
    image: couchdb:latest
    container_name: db
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
