[uwsgi]
wsgi-file = wsgi.py
callable = APP

master = true
processes = 1


socket= /tmp/uwsgi.socket
; https = 127.0.0.1:8081,./ssl/ca.crt,./ssl/ca.key, HIGH
http = 0.0.0.0:8080
http-to = /tmp/uwsgi.socket

chmod-sock = 664
vacuum = true

die-on-term = true